### ISSUE TITLE
EatingAnimation won't work with vanilla tweaks resource pack

### ISSUE THREAD

**Issue by EGOIST1372** [Theoness1/EatingAnimation#12]
It seems that this mod won't work with popular resource pack from [vanilla tweaks](https://vanillatweaks.net/picker/resource-packs/)
my guess is in unobtrusive tab-smaller utilities resource pack is the one causing this compatibility issue
can you please fix this issue since many of my friends and I have this resource pack 
just to be sure I upload all of my resource pack selected in vanilla tweaks so you can recreate this issue
without this pack mod works
stay sus :)
[VanillaTweaks_1.18.zip](https://github.com/Theoness1/EatingAnimation/files/8024214/VanillaTweaks_1.18.zip)

**Comment by EGOIST1372** [comment]
this pack only shrinks the item size so won't be as obtrusive as it is in vanilla
so need to adapt the size only
please fix this <3

**Comment by EGOIST1372** [comment]
@Theoness1 is it fixable?

**Comment by Theoness1** [comment]
> @Theoness1 is it fixable?

ща попробую

**Comment by EGOIST1372** [comment]
I sent a feedback to the resource pack as well
I hope it get fix, either you figure it out or them
thank you

**Comment by NaiNonTH** [comment]
@Theoness1 How about only just making each food model part disappear on each stage, when resource packs are applied?

For Example:

If [] = True
   X = False

Stage 0:
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]

Stage 1:
XXXXXXXXXXXXXXXX
XXXX[][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]

Stage 2:
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXX[][]
XXXXXX[][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]

Stage 3:
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
[][][][][][][]XXXXXXXXX
[][][][][][][][][][][][]XXXX
[][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][]

Stage 4:
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
[]XXXXXXXXXXXXXXX
[][][]XXXXXXXXXXXXX
[][][][][][][][][][][][][][][][]

...yada yada yada

For an easier one, you can just make the food model parts keep disappearing like a 2x2 grid-like pattern.

**Comment by NaiNonTH** [comment]
or maybe 3x3, 4x4, and so on

**Comment by Julienraptor01** [comment]
I'm gonna make a compatible version of vanilla tweaks smaller utilities for me and i'm gonna share it.

**Comment by Julienraptor01** [comment]
> @Theoness1 
> I don't know how to add support yet, but the creator of the texture pack can add support, he will need to create json files with animation and assign animation to the item and add the item to smaller util for the animation to work.

the only thing needed is basically to add the smaller utilities parent and to change the parent used by the included pack to the smaller utilities one

**Comment by Julienraptor01** [comment]
Here it is ! Please take note that this pack isn't a merge of VT pack with this mod so VT need to be present and this pack needs to be above it to be able to properly function (because it needs to override some models
[EatingAnimation.zip](https://github.com/Theoness1/EatingAnimation/files/8497894/EatingAnimation.zip)
)

**Comment by EGOIST1372** [comment]
@Theoness1 
the resource pack @Julienraptor01 provided works and is compatible with small utilities from vanillatweaks
thanks both of you for helping to make it work
also if you are going to add this resource pack in mod's download page then close this issue but if not then keep it open so others can find the resource pack here

**Comment by Julienraptor01** [comment]
> @Theoness1 the resource pack @Julienraptor01 provided works and is compatible with small utilities from vanillatweaks thanks both of you for helping to make it work also if you are going to add this resource pack in mod's download page then close this issue but if not then keep it open so others can find the resource pack here

i'm gonna make a github repo so that he can link it in descprition so he doesn't have to include it in his mod

**Comment by EGOIST1372** [comment]
sounds good
thanks

**Comment by Julienraptor01** [comment]
Here it is
https://github.com/Julienraptor01/Eating-Animation-Smaller-Utilities-Compatibility
