### ISSUE TITLE
1.18.2 not released

### ISSUE THREAD

**Issue by TechMasterApp** [Theoness1/EatingAnimation#15]
One of my favorite mods. Please port it to 1.18.2 so that I can finish my collection of mods. Indirectly meaning to update the mod sooner every time a new minecraft version is released.

**Comment by Theoness1** [comment]
Yo, EatingAnimation mod works on 1.18.2 :Р

**Comment by Theoness1** [comment]
You need Fabric API 1.18.2 + EatingAnimation Mod = You Happy :)

**Comment by TechMasterApp** [comment]
LOL ha ha nice joke, but make sure to show 1.18.2 on your CurseForge page.

**Comment by Theoness1** [comment]
Ok

**Comment by Julian-MJK** [comment]
Oh this works for 1.18.2? You should update the Modrinth page too

**Comment by CodeF53** [comment]
Please update the modrinth page
