### ISSUE TITLE
no animation for golden carrot

### ISSUE THREAD

**Issue by OldWorldOrdr** [Theoness1/EatingAnimation#17]
Golden carrots are the primary endgame food item in mc, so its important they have an animation.

**Comment by Theoness1** [comment]
Golden carrot has animation 🤨

**Comment by OldWorldOrdr** [comment]
> Golden carrot has animation 🤨

it doesnt work for me

**Comment by Theoness1** [comment]
._. send video and your modlist

**Comment by lenabees** [comment]
If you use vanilla tweaks that can break it. That is what is happening for me right now, only the golden carrot does not have an animation. I tried going through and finding what tweak breaks it but couldn't

**Comment by Theoness1** [comment]
> If you use vanilla tweaks that can break it. That is what is happening for me right now, only the golden carrot does not have an animation. I tried going through and finding what tweak breaks it but couldn't

Unclear 🤔

**Comment by Theoness1** [comment]
> If you use vanilla tweaks that can break it. That is what is happening for me right now, only the golden carrot does not have an animation. I tried going through and finding what tweak breaks it but couldn't

I understood why (Maybe). 
Some utility for small objects in hand, covers my files with its own and the animation does not work

Maybe something else

**Comment by OldWorldOrdr** [comment]
@Theoness1 it was vanilla tweaks.  It's part of the item stitching fix.  Delete (resource pack zip)/assets/minecraft/models/item/golden_carrot.json and it will work.

**Comment by lenabees** [comment]
> @Theoness1 it was vanilla tweaks. It's part of the item stitching fix. Delete (resource pack zip)/assets/minecraft/models/item/golden_carrot.json and it will work.

Can back this up, just tried and it works. Thanks for figuring out which tweak was messing it up.
