### ISSUE TITLE
Not toggleable Integrated Resource Pack

### ISSUE THREAD

**Issue by Julienraptor01** [Theoness1/EatingAnimation#18]
I don't know why but the integrated resource pack named "supporteatinganimation" in resource pack folder of the mod is automatically active and i didn't find any other way to deactivate it than to delete it from the jar.
I tested with clean fabric install with only your mod.

**Comment by Theoness1** [comment]
?

**Comment by Julienraptor01** [comment]
![image](https://user-images.githubusercontent.com/49841713/163672234-3ddf7beb-f9b9-42e7-87f9-2254b3a172dc.png)
as you can see here there isn't the arrow to disable the pack like there is on another integrated resource pack from another mod
![image](https://user-images.githubusercontent.com/49841713/163672266-222380cb-c2c1-4178-91b4-039cee8c87ff.png)

**Comment by Theoness1** [comment]
Why do you want to turn it off?

**Comment by Julienraptor01** [comment]
Because it only contains foodplusid things that aren't useful and if it's not intended to be toggleable put all the things with the other textures so it doesn't take space on the resource pack selection screen

**Comment by Julienraptor01** [comment]
Btw i think you should make all the textures toggleable so if for any reason you want to disable the mod you can disable the resource pack. And in addition to that as i need to have a texture pack that will override your whole textures so it permit to lessen the work MC has to do if i could disable your textures when enabling my owns.

**Comment by EGOIST1372** [comment]
@Julienraptor01 that resource pack for cloak fix is unnecessary since you can have that from vanillatweaks pack and it doesn't need CEM to work :D

**Comment by Julienraptor01** [comment]
@EGOIST1372 

1. sadly the cloak fix pack from vanilla Tweaks doesn't fix the models but instead simply remove pixels from only the villager texture and not from other affected mobs
But this isn't related at all to my issue
(btw if you want ot take a look at what this pack does it's made by me so you can find by searching cloak fix through my repos) 

2. The multiple pack that you can see with an icon that ressemble to VT's one are private custom packs made by me that integrates many VT Tweaks and all have differents purposes

**Comment by EGOIST1372** [comment]
oh cool thanks for info :D
