### ISSUE TITLE
Issues link in curseforge redirect to a wrong link

### ISSUE THREAD

**Issue by EGOIST1372** [Theoness1/EatingAnimation#19]
the link it redirect to is this [link](https://github.com/Theoness1/EatingAnimation/issues/1)
screenshot
![image](https://user-images.githubusercontent.com/86555131/163713996-eeeb1708-41b0-4f49-b138-d20f8a751b68.png)

the correct link that it should redirect to is this [link](https://github.com/Theoness1/EatingAnimation/issues)

**Comment by EGOIST1372** [comment]
that's pretty sus ngl :D

**Comment by Theoness1** [comment]
ok
