### ISSUE TITLE
EatingAnimations Breaks tool and weapon textures in Visual Enchantments Resource Pack

### ISSUE THREAD

**Issue by AlfmanOO7** [Theoness1/EatingAnimation#20]
![image](https://user-images.githubusercontent.com/62825044/167614188-6facb206-1f5c-4b94-b038-c5cb1311b1b8.png)
Tools and Weapons should be textured differently to vanilla textures
Pack: https://www.curseforge.com/minecraft/texture-packs/visual-enchantments

**Comment by Theoness1** [comment]
Yo, oops.

hmm i'll try to figure it out

**Comment by Julienraptor01** [comment]
This pack needs CIT so https://github.com/Theoness1/EatingAnimation/pull/16 to work (or another fix if you have another one)
This is a duplicate of #9

**Comment by Theoness1** [comment]
fixed soon
