### ISSUE TITLE
[Mod Support Request] Compatibility with Expanded Delight mod.

### ISSUE THREAD

**Issue by DatuStram** [Theoness1/EatingAnimation#22]
I love how you've added compatibility with Farmer's Delight, it really is an awesome update! 

When you have the time to spare, could you maybe add compatibility with its expansion, Expanded Delight?

You can find said mod [here - Modrinth](https://modrinth.com/mod/expanded-delight) or [here - CurseForge](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)

Thank you very much for your work ❤️

**Comment by Theoness1** [comment]
ok
