### ISSUE TITLE
[Some Mod Compatibility Ideas]

### ISSUE THREAD

**Issue by Pirogiran** [Theoness1/EatingAnimation#26]
I was going through a my list of mods and thought you might be interested in a small list of mod compatibility ideas:

Immersive Weathering (4 items)
BetterNether (5 food items and 2 "Medicine" items)
BetterEnd (14 items)
Bewitchment (9 items?)
Bewitchment Plus (just Dragon Fruit?)
Terrarian Slimes (just Apple Pie and Ice Cream)
Go Fish (40 items)
MobZ (just Thick Rotten Flesh)
Nears  (10 items)
Better Animals Plus (15 items)
Adorn (4 items)
Create [Fabric] (5 items?)
Reaping Mod (1 item)

But this are only **ideas** (for 113 items, yes...) for 1.18.2.
And thanks for awesome mod!
P.S.: "?' means "idk exactly".

**Comment by Theoness1** [comment]
most mods have a license that prevents me from using their assets D:

**Comment by Pirogiran** [comment]
> license that prevents me from using their assets

Oh..... What a shame...
Okey, thanks for the response!

**Comment by Pirogiran** [comment]
And, i think, making texture pack to change their textures and than making compatibility is some stupid idea :/

**Comment by Julienraptor01** [comment]
> most mods have a license that prevents me from using their assets D:

Well maybe if you discuss with them some will be compilant and authorize you to do the compatibility ?

**Comment by Redd56** [comment]
adding fish of thieves
