### ISSUE TITLE
CIT Textures Conflicting

### ISSUE THREAD

**Issue by sirmitchu** [Theoness1/EatingAnimation#28]
Something about the way the mod uses CIT makes it so certain resource packs that rely on CIT data, such as Xali's Enchanted Books, don't show custom textures in the inventory. I've only tested this with Xali's Enchanted Books, but I imagine this same issue would occur with other resource packs that rely on CIT.

**Comment by Theoness1** [comment]
you see this on 1.19 ?
Send screenshot

**Comment by sirmitchu** [comment]
On 1.19. Textures don't show up in inventories but do on the ground and in your hand. 
![2022-08-12_22 03 14](https://user-images.githubusercontent.com/111154110/184469361-5cbb333c-11d6-49d0-a7a2-bc224cd4d02d.png)
![2022-08-12_22 03 42](https://user-images.githubusercontent.com/111154110/184469364-7e575882-f092-4252-9e2d-366773d2fe5b.png)

**Comment by sirmitchu** [comment]
I'm running the texture pack with CIT Resewn 1.19 Fabric.

**Comment by Theoness1** [comment]
and you download last mod version 1.19 ?

**Comment by Theoness1** [comment]
Because I checked on another texture pack and there were changes on the books, but everything worked

**Comment by sirmitchu** [comment]
Ahh! Realized I was running the previous 1.19 version. I see the 1.19.2 version fixes the CIT issues. Works like a charm now.
