### ISSUE TITLE
[1.18.2] [Mod Compat] Expanded Delight & Nether's Delight

### ISSUE THREAD

**Issue by ConqAra** [Theoness1/EatingAnimation#30]
Since Farmer's Delight is supported, can you add support for [Expanded Delight ](https://modrinth.com/mod/expanded-delight) and [Nether's Delight](https://www.curseforge.com/minecraft/mc-mods/nethers-delight-fabric) for Fabric?

**Comment by Julienraptor01** [comment]
this is a partial dupe of #22

**Comment by Theoness1** [comment]
чо?

**Comment by Theoness1** [comment]
> Since Farmer's Delight is supported, can you add support for [Expanded Delight ](https://modrinth.com/mod/expanded-delight) and [Nether's Delight](https://www.curseforge.com/minecraft/mc-mods/nethers-delight-fabric) for Fabric?

Expanded is supported

**Comment by Theoness1** [comment]
Nethers Delight has private textures

**Comment by ConqAra** [comment]
oh it was 1.18.2 that didnt have the compat for expanded delight. My bad.
