### ISSUE TITLE
[SUGGESTION]: Add a way to add support for a mod manually

### ISSUE THREAD

**Issue by TrueVenomized** [Theoness1/EatingAnimation#31]
Basically, it would be cool if it was possible to (since based on the mod compatibility ideas post you can't have it in the actual mod) add compatibility for edible items from other mods.
Like the textures could be made manually (by anyone really) and then people (unless it's just me) can stop being annoyed that only half of their foods animate when eaten.
Basically I want a way to add support for modded foods (and non-foods that are edible) myself so I can stop having only half of my foods animated.

*Though this suggestion is on the Fabric version, obviously it would be nice to have on forge, too*

**Comment by Theoness1** [comment]
Support is done, you can add the necessary files for the items yourself, or send it to me, if I like it, then all people will use it

**Comment by TrueVenomized** [comment]
How do you add the support for the modded items? Would you just use the items namespace?
For example, if the item was Green Steak, and the namespace was green_steak, would you name the texture files as follows?:
green_steak_eating_0.png, green_steak_eating_1.png, green_steak_eating_2.png, etc...

**Comment by Theoness1** [comment]
see packages for mods items
