### ISSUE TITLE
Golden carrots are not animated

### ISSUE THREAD

**Issue by XAURAVUS** [Theoness1/EatingAnimation#34]
Golden carrots are (arguably) the best food item in the vanilla game, so it's unfortunate that golden carrots are the only vanilla food without an animation. Would love to see an animation added :)

**Comment by Theoness1** [comment]
Golden carrot animated

**Comment by Un1q32** [comment]
if you use vanilla tweaks with fix item stitching, it breaks the mod, go into your resource pack and delete all files that modify the golden carrot
