### ISSUE TITLE
Incompatibility with CustomModelData in Inventory view.

### ISSUE THREAD

**Issue by Fiopon** [Theoness1/EatingAnimation#35]
While you can use CustomModelData with eating animations in the hand and third person, the inventory item does not respect the CustomModelData predicate.

Inventory item will ONLY display the default item model, not applying any predicates.

Suggestion: Grab the Inventory model from the predicate "eating" when it is 0

Steps to Reproduce:
Install this Test Resource Pack
[CustomModelData EatingAnimation.zip](https://github.com/Theoness1/EatingAnimation/files/10471200/CustomModelData.EatingAnimation.zip)
Ingame, run the following Commands:
`/give @s bread` = Default Bread
`/give @s bread{CustomModelData:1}` = Beef Taco
`/give @s bread{CustomModelData:2}` = Pork Taco
`/give @s bread{CustomModelData:3}` = Chicken Taco
`/give @s bread{CustomModelData:4}` = Fish Taco
`/give @s bread{CustomModelData:5}` = Beef Wellington
Notice the items in the inventory all use the default model present in bread.json instead of the CustomModelData versions, but inhand and inworld, they appear properly.

**Comment by Theoness1** [comment]
fixed
