### ISSUE TITLE
Problem with Golden Carrot eating animation

### ISSUE THREAD

**Issue by charcoalpt** [Theoness1/EatingAnimation#37]
So I have recently found a problem that the Golden Carrot eating animation isn't loaded while the others works fine. I have tried opening the mod file as archive (7-Zip) but the golden_carrot.json file and the "children" are just perfectly fine.

Sidenote: I have once tried to retexture the Enchanted Golden Apple eating texture to sync with the Visual Enchantments texture pack and it worked once, but the second time when I reload the pack, it got the same issue as the current one above.

**Comment by Theoness1** [comment]
if you use other resourcepack, you need to animate food in your resourcepack.
