### ISSUE TITLE
I'm not able to see the Eating animation (help)

### ISSUE THREAD

**Issue by AxuuIsLost0** [Theoness1/EatingAnimation#43]
I'm not able to see the eating animation although i've disabled every other mod (I'm in version 1.20.1

**Comment by makumaku1974** [comment]
same here

**Comment by Theoness1** [comment]
> I'm not able to see the eating animation although i've disabled every other mod (I'm in version 1.20.1

if you use vanilla tweaks with smaller items, mod doesn't work.
