### ISSUE TITLE
[Mod Support] Naturalist

### ISSUE THREAD

**Issue by MrGreenTea** [Theoness1/EatingAnimation#47]
Hi, love the mod and look of it!

I was wondering if you'd be willing to add support for the foods added by the [Naturalist](https://modrinth.com/mod/naturalist) mod.

These are:
- (Cooked) Venison
- (Cooked) Lizard Tail
- (Cooked) Duck
- (Cooked) Bass
- (Cooked) Catfish
- Cooked Egg

**Comment by Theoness1** [comment]
This mod has ARR license, soo :(

**Comment by MrGreenTea** [comment]
Oh right, I will ask the author if we can do something with that.

**Comment by MrGreenTea** [comment]
The author said to send you to his discord, so that's what I am doing :)

Here is the message: https://discord.com/channels/878598895788240936/981553419292672060/1167127440615805030

**Comment by crispytwig** [comment]
> This mod has ARR license, soo :(

Hello! You have our permission to use the food assets in your mod for the purpose of compatibility. You may redistribute edited versions in your mod but you may not take credit for them as if they were original pieces.

_(This only applies to the creator being responded to, no other assets may be redistributed without permission)_

Consider this written permission and message me if you have any more questions! My Discord is also "crispytwig". :-)

**Comment by Theoness1** [comment]
Mod support done, wait for update! ඞ
