### ISSUE TITLE
[Mod Support] Hybrid Aquatic

### ISSUE THREAD

**Issue by MrGreenTea** [Theoness1/EatingAnimation#48]
I was wondering if you would be open to adding support for the fish meats added by [Hybrid Aquatic](https://modrinth.com/mod/hybrid-aquatic)

These are:
- (Cooked) Fish Meat
- (Cooked) Small Fish Meat
- (Cooked) Tentacle
- (Cooked) Crab Meat

**Comment by Theoness1** [comment]
Ok

**Comment by Theoness1** [comment]
done, update soon
