### ISSUE TITLE
Suggestion and a way to make: all food animations.

### ISSUE THREAD

**Issue by DanielGolan-mc** [Theoness1/EatingAnimation#5]
My suggestion is, to add support to all foods. How?

1. For any tick the food takes to it, the mod will take the previous tick's texture, and add delete some blobs. The blobs are starting to generate in texture boundaries, and move inwards. The blobs got a higher chance to occur the far it is from the player hand.
2. Delete the blobs (make a texture with the blobs as transparent)
3. Show it.
4. The blobs vary. They're smaller the healthy the food is (gives more hunger points) and occuring more the light it is (how much time it takes to it the food)
5. When food with vanilla texture, (for example: bottle, bowl) the pixels of container will not disappear.
6. Mods can add to the tag `food_containers` items that will be counted as bowls.

**Comment by Theoness1** [comment]
this is a cool idea, but VERY inconvenient
