### ISSUE TITLE
[Mod Support] Farmer's Delight New Food Items

### ISSUE THREAD

**Issue by avilonlegends** [Theoness1/EatingAnimation#50]
Hi there!

 In version 1.3.7 of Farmer's Delight (Fabric), posted on Modrinth on Nov 22, 2022, a couple new food items were added which so far are not supported by Eating Animations.
 These food items include: glow berry custard, salmon roll, cod roll, kelp roll, kelp slice roll, mushroom rice and bone broth.
 
 Could you perhaps add support for these as well?

**Comment by Theoness1** [comment]
ok, i do that

**Comment by Theoness1** [comment]
I hope I'll do it soon !!! ඞඞඞ

**Comment by Theoness1** [comment]
done, update soon
