### ISSUE TITLE
[Bug] Custom item texture with resource pack via nbt

### ISSUE THREAD

**Issue by Player505** [Theoness1/EatingAnimation#51]
I noticed that if you have food with a custom item texture specified by said items NBT while you have this mod installed the item texture will revert to the base texture of the item in the inventory. Holding the item gives you correct texture. Disablinging the resourceback provided by the mod doesn't change anything.

Ideally it would be nice if the item references a custom model in the NBT the mod just ignores it. Alternatively make it so disabling the resource pack disables changing any textures rather than needed to reload the instance to diable the mod altogether.

**Comment by Theoness1** [comment]
> I noticed that if you have food with a custom item texture specified by said items NBT while you have this mod installed the item texture will revert to the base texture of the item in the inventory. Holding the item gives you correct texture. Disablinging the resourceback provided by the mod doesn't change anything.
> 
> Ideally it would be nice if the item references a custom model in the NBT the mod just ignores it. Alternatively make it so disabling the resource pack disables changing any textures rather than needed to reload the instance to diable the mod altogether.

you need to download this modVersion: https://legacy.curseforge.com/minecraft/mc-mods/eating-animation-fabric/files/4823518

**Comment by Player505** [comment]
Fixed thank you
