### ISSUE TITLE
[Mod Support] The Bumblezone

### ISSUE THREAD

**Issue by AstardGrimoire** [Theoness1/EatingAnimation#52]
Can you add eating animation forThe Bumblezone's mod food?
This mod adds 5 food items:
Shugar water bottle
Bee bread
Honey crystal shard
Bee soup
Royal jelly bottle

**Comment by TelepathicGrunt** [comment]
While not a food item, the Essence of the Bees item does use the eating action to be consumed and could use an animation

Also, I am the Bumblezone dev and I am hereby giving Eating Animation dev permission to use my textures to add this modded feature compat

**Comment by Theoness1** [comment]
I hope I'll do it soon !!! ඞඞඞ

**Comment by Theoness1** [comment]
done, update soon
