### ISSUE TITLE
[Mod support] Botania

### ISSUE THREAD

**Issue by anoomolu** [Theoness1/EatingAnimation#53]
Hiya, thanks for making this really cute mod.

Botania has two food items that might be worth animating:

- Mana cookies, with the same animation style as regular cookies
- Fruit of Grisaia. For this, it could be cool to have the apple animation go halfway (almost to the core), but then reverse, since the fruit isn't actually consumed.

**Comment by AstardGrimoire** [comment]
You forgot mana bottle

**Comment by anoomolu** [comment]
> You forgot mana bottle

Mana bottle has multiple uses, each one reducing the amount of mana left in it. I thought it wasn't necessary, but ig you could have small decrements between levels.

**Comment by Theoness1** [comment]
I hope I'll do it soon !!! ඞඞඞ

**Comment by Theoness1** [comment]
done, update soon
