### ISSUE TITLE
CustomCrops incompatibility

### ISSUE THREAD

**Issue by ChrissW-R1** [Theoness1/EatingAnimation#55]
This mod has a little incompatibility with Custom Crops.
https://polymart.org/resource/customcrops.2625

Custom crops have sprite as apples. So holding in hand or showing in item frames it works fine, but in the inventory all crops are apples, which is a little bit confusing.

![2024-03-30_10 48 11](https://github.com/Theoness1/EatingAnimation/assets/1086210/f08b811f-d46f-40fd-a8d3-40e6f1a003a9)
![2024-03-30_10 50 21](https://github.com/Theoness1/EatingAnimation/assets/1086210/a9d0dd42-fb33-427b-9bdc-3aca1e571352)
![2024-03-30_10 53 04](https://github.com/Theoness1/EatingAnimation/assets/1086210/7962d3d5-3053-4121-a56e-e6b218af6148)

**Comment by Theoness1** [comment]
You need to download this version 
![image](https://github.com/Theoness1/EatingAnimation/assets/89033436/2d23917d-dfb3-49a9-892e-e0b2ac84521e)
https://curseforge.com/minecraft/mc-mods/eating-animation-fabric/files/4823518
