### ISSUE TITLE
EatingAnimation breaks CustomModelData models

### ISSUE THREAD

**Issue by Tikkle** [Theoness1/EatingAnimation#57]
Hello,

I have a resourcepack making 2d items have different textures with CustomModelData. The texture applies to the item when it is being held in your hand, dropped on the ground, or placed in an item frame.

However, the item does not have its texture applied in the inventory. Upon removing EatingAnimation from my mods list, the texture was applied correctly.

Version: MC 1.20.4
EatingAnimation: 1.9.61

## With Eating Animation installed:
![2024-04-02_02 24 53](https://github.com/Theoness1/EatingAnimation/assets/14956067/2c109047-7bf5-45d1-8b07-2df5243f4188)

## Without Eating Animation installed:
![2024-04-02_12 52 20](https://github.com/Theoness1/EatingAnimation/assets/14956067/dbcdb68d-9a03-47a4-83ae-3b8c6629fcdc)

**Comment by Theoness1** [comment]
You need to download this version
https://curseforge.com/minecraft/mc-mods/eating-animation-fabric/files/4823518
